// 1. creamos una variable para guardar el valor del contador
let contador = 0;

// 2. capturamos los elementos del  html usando el id
const elamentonumero = document.getElementById("numero");
const btnsumar = document.getElementById("btnsumar");
const btnrestar = document.getElementById("btnrestar");
const elementomensaje = document.getElementById("mensaje");

// 3. agregamos eventos a los botones