let Nombre, edad, direccion, movil, email;

nombre = prompt("digite su nombre; ") //se pide al usuari
edad = prompt("digite su edad; ") //se pide al usuari
direccion = prompt("digite su direccion; ") //se pide al usuari
movil = prompt("digite su movil; ") //se pide al usuar
email = prompt("digite su email; ") //se pide al usuar

console.log("tu nombre es: ", nombre);
console.log("tu edad es: ", edad);
console.log("tu direccio es: ", direccio);
console.log("tu movil es: ", movil);
console.log("tu email es: ", email);

document.writeln("tu nombre es: ", nombre, "<br>");
document.writeln("tu edad es: ", edad, "<br>");
document.writeln("tu direccion es: ", direccion, "<br>");
document.writeln("tu movil es: ", movil, "<br>");
document.writeln("tu email es: ", email, "<br>");